### PR TITLE
(Story)Pointless PR

### PR DESCRIPTION
**Pull request by theoboldalex**
image

### CODE REVIEW

**Comment by matthewrobinsondev** [comment]
0 test coverage, how many story points to add tests?

**Comment by theoboldalex** [comment]
Lemme ask the PO if I'm allowed to write tests and I'll get back to you after we refine the ticket for it.

**Comment by vaugenwake** [comment]
Want to add a spike ticket for that 🤣

**Comment by vaugenwake** [comment]
We will circle back on this, after we have reviewed the business value and connected with out stakeholders on the synergy on a way forward. 🤣

**Pull request closed without merging**
